### ISSUE TITLE
Add this resource to resource-types.concourse-ci.org

### ISSUE THREAD

**Issue by username-is-already-taken2** [navicore/teams-notification-resource#16]
Hi there

Thanks very much for this resource, I make use of it a lot.

Would you have any objections if I was to add this to the resource-types page on the concourse-ci.org website?

Would help share the love with a few more people?

Let me know what you think

Best Regards

Gary

**Comment by navicore** [comment]
> Would you have any objections if I was to add this to the resource-types page on the concourse-ci.org website?
> 
> Would help share the love with a few more people?

Gary, that would be great.  Yes please.  Thanks!!
