### ISSUE TITLE
Feature Request: Read message from file similar to Slack Notification Resource

### ISSUE THREAD

**Issue by BlacktoBlue** [navicore/teams-notification-resource#3]
Can we please have a text_file parameter like in https://github.com/cloudfoundry-community/slack-notification-resource. I am currently trying to send notifications to both Slack and Teams.

**Comment by navicore** [comment]
Hi @BlacktoBlue , thx for the suggestion.  I'll give it a try towards the end of the week and report back here.

**Comment by abracadv8** [comment]
Accepting PRs?

**Comment by navicore** [comment]
Thx @abracadv8 for the PR.  Merging now.

No CLA.  New image should be on docker hub shortly.  Thanks !!
